import type { GraphData, GraphEdge, GraphNode, Jurisdiction, RequirementGroup, Source } from "../types";
import jurisdictionRows from "./graph/jurisdictions.json";
import { seedBundleModules } from "./graph/manifest";

export { validateGraph, type GraphIssue } from "./validate";

/**
 * The single seam the rest of the product loads data through.
 *
 * No government fact lives in TypeScript. Schemes, documents, offices, fees,
 * eligibility rules and the quotes behind them are rows, because government
 * requirements change and a fact that needs a rebuild and a redeploy to
 * correct is a fact that stays wrong. Code holds the compiler and the rule
 * evaluator, nothing else.
 *
 * The JSON under `graph/` is the seed: the same rows the database is loaded
 * from, checked in so tests, CI and a laptop with no network still work.
 * `loadGraphFrom` is what the database loader calls once rows are live.
 */

/** One journey's worth of rows. The unit both the seed files and the DB use. */
export interface GraphBundle {
  id: string;
  sources: Source[];
  nodes: GraphNode[];
  edges: GraphEdge[];
  requirementGroups: RequirementGroup[];
  questions: GraphData["questions"];
  /**
   * Escalation only. CPGRAMS and SWAGAT are not tied to one department, so
   * rather than writing the same two edges onto forty services by hand they
   * are stored once with `*` where the service id goes, and stamped out at
   * load time. Kept apart from `edges` because `*` is not a node and the
   * validator is right to say so.
   */
  edgeTemplates?: GraphEdge[];
}

/**
 * JSON arrives untyped and is cast here, once, at the only door it comes
 * through. What TypeScript used to catch at compile time, `validateGraph` now
 * catches at load time, including every enum. That check runs in CI and in
 * `pnpm graph:validate`, so a bad row fails the build the same as a bad type
 * used to.
 *
 * The list itself is generated by `pnpm bundles:build` from what is in
 * `graph/`, because it used to be typed here by hand and in two other places
 * that disagreed with it. Drop a bundle in the folder, run the generator.
 */
const seed = seedBundleModules as unknown as GraphBundle[];

/** Every seeded bundle, escalation included, for the tools that push rows. */
export const seedBundles: GraphBundle[] = seed;
export const seedJurisdictions = jurisdictionRows as unknown as Jurisdiction[];

/** The journey bundles, without the shared escalation templates. */
export const seedJourneys: GraphBundle[] = seed.filter((b) => !b.edgeTemplates);

export function loadGraphFrom(bundles: GraphBundle[], jurisdictions: Jurisdiction[]): GraphData {
  const nodes = bundles.flatMap((b) => b.nodes);
  const templates = bundles.flatMap((b) => b.edgeTemplates ?? []);
  const services = nodes.filter((n) => n.type === "SERVICE");

  return {
    jurisdictions,
    nodes,
    edges: [
      ...bundles.flatMap((b) => b.edges),
      ...services.flatMap((s) => templates.map((t) => ({ ...t, id: t.id.replace("*", s.id), from: s.id }))),
    ],
    requirementGroups: bundles.flatMap((b) => b.requirementGroups),
    sources: bundles.flatMap((b) => b.sources),
    questions: dedupeQuestions(bundles.flatMap((b) => b.questions)),
  };
}

let cached: GraphData | undefined;

/**
 * The seed, synchronously. Always works, needs no network and no credentials,
 * which is what tests, the CLIs and a laptop on a train use.
 */
export function loadGraph(): GraphData {
  cached ??= loadGraphFrom(seed, seedJurisdictions);
  return cached;
}

/**
 * The database backed loader lives in `../server`, not here, and is reached
 * through `@ariane/core/server`. A browser bundle that can see it drags the
 * whole Supabase SDK in behind it, which is 64kB of a citizen's data plan
 * spent on a client that will never open a socket to Postgres.
 */

/** Journeys share fields like `age`. First definition wins. */
function dedupeQuestions<T extends { field: string }>(questions: T[]): T[] {
  const seen = new Set<string>();
  return questions.filter((q) => !seen.has(q.field) && seen.add(q.field));
}
