// Generated by scripts/bundles.mjs. Do not edit by hand.
// Add a bundle by dropping its .json in this folder and running: pnpm bundles:build
import certificates from "./certificates.json";
import districtCertificates from "./district-certificates.json";
import drivingLicence from "./driving-licence.json";
import pension from "./pension.json";
import permitsAndLicences from "./permits-and-licences.json";
import pf from "./pf.json";
import propertyAndLand from "./property-and-land.json";
import scholarship from "./scholarship.json";
import welfareSchemes from "./welfare-schemes.json";
import escalation from "./escalation.json";

/** Every bundle file in this folder, journeys first, templates last. */
export const seedBundleModules: unknown[] = [certificates, districtCertificates, drivingLicence, pension, permitsAndLicences, pf, propertyAndLand, scholarship, welfareSchemes, escalation];

/** Same order, as ids. */
export const seedBundleNames = ["certificates", "district-certificates", "driving-licence", "pension", "permits-and-licences", "pf", "property-and-land", "scholarship", "welfare-schemes", "escalation"] as const;

/**
 * The ones with a docs/research file behind them, so `quotes:audit` knows what
 * to audit without keeping its own copy of the list.
 */
export const journeyBundleNames = ["certificates", "district-certificates", "driving-licence", "pension", "permits-and-licences", "pf", "property-and-land", "scholarship", "welfare-schemes"] as const;
