// Generated by scripts/bundles.mjs. Do not edit by hand.
// Add a bundle by dropping its .json in this folder and running: pnpm bundles:build
import birthDeath from "./birth-death.json";
import certificates from "./certificates.json";
import districtCertificates from "./district-certificates.json";
import drivingLicence from "./driving-licence.json";
import gst from "./gst.json";
import msmeAndUdyam from "./msme-and-udyam.json";
import offices from "./offices.json";
import pan from "./pan.json";
import pension from "./pension.json";
import permitsAndLicences from "./permits-and-licences.json";
import pf from "./pf.json";
import propertyAndLand from "./property-and-land.json";
import rationCard from "./ration-card.json";
import scholarship from "./scholarship.json";
import startup from "./startup.json";
import welfareSchemes from "./welfare-schemes.json";
import escalation from "./escalation.json";

/** Every bundle file in this folder, journeys first, templates last. */
export const seedBundleModules: unknown[] = [birthDeath, certificates, districtCertificates, drivingLicence, gst, msmeAndUdyam, offices, pan, pension, permitsAndLicences, pf, propertyAndLand, rationCard, scholarship, startup, welfareSchemes, escalation];

/** Same order, as ids. */
export const seedBundleNames = ["birth-death", "certificates", "district-certificates", "driving-licence", "gst", "msme-and-udyam", "offices", "pan", "pension", "permits-and-licences", "pf", "property-and-land", "ration-card", "scholarship", "startup", "welfare-schemes", "escalation"] as const;

/**
 * The ones with a docs/research file behind them, so `quotes:audit` knows what
 * to audit without keeping its own copy of the list.
 */
export const journeyBundleNames = ["birth-death", "certificates", "district-certificates", "driving-licence", "gst", "msme-and-udyam", "offices", "pan", "pension", "permits-and-licences", "pf", "property-and-land", "ration-card", "scholarship", "startup", "welfare-schemes"] as const;
