// Generated by scripts/bundles.mjs. Do not edit by hand.
// Add a bundle by dropping its .json in this folder and running: pnpm bundles:build
import certificates from "./certificates.json";
import drivingLicence from "./driving-licence.json";
import pension from "./pension.json";
import pf from "./pf.json";
import scholarship from "./scholarship.json";
import escalation from "./escalation.json";

/** Every bundle file in this folder, journeys first, templates last. */
export const seedBundleModules: unknown[] = [certificates, drivingLicence, pension, pf, scholarship, escalation];

/** Same order, as ids. */
export const seedBundleNames = ["certificates", "driving-licence", "pension", "pf", "scholarship", "escalation"] as const;

/**
 * The ones with a docs/research file behind them, so `quotes:audit` knows what
 * to audit without keeping its own copy of the list.
 */
export const journeyBundleNames = ["certificates", "driving-licence", "pension", "pf", "scholarship"] as const;
