/**
 * Render the Gujarat government domain registry as markdown.
 *
 *   pnpm domains:build           # writes docs/gujarat-domains.md
 *   pnpm domains:build --check   # fails if the file on disk is stale
 *
 * All the thinking lives in `scripts/lib/registry.mjs`, which both this and
 * `pnpm domains:classify` read. This file is a renderer and nothing else: it
 * makes zero network calls and holds zero opinions about what a host is.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { buildRegistry, CATEGORIES } from "./lib/registry.mjs";

const root = new URL("../", import.meta.url);
const registry = buildRegistry();

const count = (c) => registry.filter((r) => r.category === c).length;
const named = registry.filter((r) => r.name).length;

const out = [];
out.push("# Gujarat government websites");
out.push("");
out.push("Generated by `pnpm domains:build`. Do not edit by hand, the edit will be");
out.push("overwritten. Change the inputs instead:");
out.push("");
out.push("- `docs/research/domains/gujarat-hosts.txt` for hosts that exist");
out.push("- `docs/research/domains/gswan-department-directory.tsv` for what they do");
out.push("");
out.push("**Nothing here has been fetched.** This is a map of where to look, built from a");
out.push("host capture and the state's own published department directory. It is not");
out.push("evidence and must never be cited to a citizen: a claim about a fee, a document");
out.push("or an eligibility rule needs a verbatim quote and a retrieval date in the");
out.push("research JSON, which is a different file for a reason.");
out.push("");
out.push(`${registry.length} hosts, ${named} of them named by the government itself.`);
out.push("");
out.push("| Category | Hosts |");
out.push("| --- | ---: |");
for (const [key, label] of CATEGORIES) {
  const n = count(key);
  if (n) out.push(`| ${label} | ${n} |`);
}
out.push(`| **Total** | **${registry.length}** |`);
out.push("");

for (const [key, label] of CATEGORIES) {
  const rows = registry.filter((r) => r.category === key);
  if (!rows.length) continue;
  out.push(`## ${label}`);
  out.push("");
  if (key === "INFRASTRUCTURE") {
    out.push("Mail, DNS, load balancers, staging copies and build tooling. Listed so nobody");
    out.push("spends an afternoon working out whether `ns2` is a citizen service.");
    out.push("");
  }
  if (key === "DEAD") {
    out.push("Enumerated once, no longer resolving. Kept rather than deleted: a host that");
    out.push("stopped answering is a fact about the estate, and dropping it from the file");
    out.push("just means the next capture rediscovers it and someone checks it again.");
    out.push("");
  }
  if (key === "UNCLASSIFIED") {
    out.push("Real hosts the department directory does not cover and no naming rule matches.");
    out.push("This is the work queue: each one needs a human to say what it is, and that is");
    out.push("one line added to the TSV, not a scrape.");
    out.push("");
  }
  out.push("| Host | What it is | Department | Basis |");
  out.push("| --- | --- | --- | --- |");
  for (const r of rows) {
    const name = r.name ? (r.sections ? `${r.name} (+${r.sections - 1} sections)` : r.name) : "_not yet identified_";
    out.push(`| \`${r.host}\` | ${name} | ${r.department ?? "-"} | ${r.basis} |`);
  }
  out.push("");
}

const markdown = out.join("\n");
const target = fileURLToPath(new URL("docs/gujarat-domains.md", root));

if (process.argv.includes("--check")) {
  const current = (() => {
    try {
      return readFileSync(target, "utf8");
    } catch {
      return null;
    }
  })();
  if (current !== markdown) {
    console.error("docs/gujarat-domains.md is stale. Run: pnpm domains:build");
    process.exit(1);
  }
  console.log(`docs/gujarat-domains.md is current, ${registry.length} hosts`);
} else {
  writeFileSync(target, markdown);
  console.log(`docs/gujarat-domains.md written, ${registry.length} hosts, ${named} named`);
  for (const [key, label] of CATEGORIES) {
    const n = count(key);
    if (n) console.log(`  ${String(n).padStart(4)}  ${label}`);
  }
}
